name: Continuous Integration
on:
    push:
        branches:
            - 'develop'
            - 'master'
            - 'ci/*'
    pull_request:
        branches:
            - 'develop'
            - 'master'

jobs:
    server:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        strategy:
            fail-fast: false
            matrix:
                packmode: ['normal', 'expert']
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '11'

            - name: Setting mode to ${{ matrix.packmode }}
              run: |
                  node .github/actions/packmode.js ${{ matrix.packmode }} > mode.json
                  cat mode.json

            - run: bash ./InstanceSyncSetup.sh
              working-directory: ./automation
            - run: pwsh ./update-server.ps1 ${{ github.ref_name }} world backups $true $false
              working-directory: ./automation

            - name: Setting eula to true
              run: |
                  echo "eula=true" > eula.txt
                  cat eula.txt

            - run: node .github/actions/start-server.js bash ./start-automated-server.sh

            - run: node .github/actions/log-kubejs-warnings.js
            - run: node .github/actions/kubejs-recipes.js

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: server (${{ matrix.packmode }})
                  path: |
                    ./*/crash-reports/
                    ./*/logs/
                    ./*/kubejs/exported/recipes/
