name: Update Modlist
on:
  push:
#    paths:
#      - 'minecraftinstance.json'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Run actions/setup-npm@v3
        run: cd automation/node && npm install

      - run: echo ${{ github.EVENT_NAME }}
      - run: echo ${{ JSON.stringify(github.event) }}
      - run: node automation/node/new-modlist.js ${{ github.token }} ${{ github.event.push.repository.owner.name }} ${{ github.event.push.repository.name }} ${{ github.event.push.ref }}
