name: Update Modlist

on:
  push:
    branches:
      - 'develop'
      - 'modlist/**'
    paths:
      - MODLIST.md
      - minecraftinstance.json
      - automation/settings.ps1
      - .github/workflows/modlist.yml
      - automation/node/modlist-generate.js

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3

      - run: npm install
        working-directory: automation/node

      - run: node automation/node/modlist-generate.js

      - name: Run git commit
        run: |          
          git diff --exit-code MODLIST.md || (git add MODLIST.md && git commit -m "Update MODLIST.md")
          git push
        env:
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com
          GIT_AUTHOR_NAME: $(git log -n 1 --pretty=format:%an minecraftinstance.json)
          GIT_AUTHOR_EMAIL: $(git log -n 1 --pretty=format:%ae minecraftinstance.json)
          GIT_AOTHOR_EMAIL: "$(git log -n 1 --pretty=format:%ae minecraftinstance.json)"
