name: Update Modlist
on:
  push:
#    paths:
#      - 'minecraftinstance.json'
#      - 'automation/node/new-modlist.js'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Run actions/setup-npm@v3
        run: cd automation/node && npm install

#      - run: echo '${{ toJSON(github) }}'
      - run: node automation/node/new-modlist.js ${{ github.token }} ${{ github.event.repository.owner.name }} ${{ github.event.repository.name }} ${{ github.ref_name }}
